### ISSUE TITLE
Try using alpine-based docker image (musl locale issues)

### ISSUE THREAD

**Issue by jantman** [jantman/biweeklybudget#125]
The Docker image for this is based on the non-alpine (debian) variant of the official Python image, which is 535 MB as opposed to 89 MB for alpine.

**Comment by jantman** [comment]
Tried work on this in ``noci-issues/125`` branch, as of 152f1a6dec670317f64c346c8d59689c4afe326e

Doesn't work. Alpine Linux is based on the musl C library, which doesn't have locale support. As a result, our many calls to ``locale.currency()`` fail with:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/locale.py", line 262, in currency
    raise ValueError("Currency formatting is not possible using "
ValueError: Currency formatting is not possible using the 'C' locale.
```

This issue needs to either wait for a usable musl locale support, or some non-Alpine (non-musl) tiny base image.

**Comment by jantman** [comment]
Ok, I've found a solution to this problem. The [babel](http://babel.pocoo.org/en/latest/index.html) package is specifically designed to aid i18n and l10n in Python web applications, and has a [format_currency](http://babel.pocoo.org/en/latest/api/numbers.html#babel.numbers.format_currency) function that doesn't rely on locale support, and works correctly in the Alpine-based Docker images. The function takes three arguments; the value to format, the currency specifier (i.e. 'USD') and the locale (i.e. 'en_US'). This does mean (see also #140 ) that we should probably make the currency specifier a configuration value, and should probably make the locale a configuration value as well, that we attempt to get from the environment/system if possible (or at least allow it to be overridden via env vars).

**Comment by jantman** [comment]
When I try this, bump to the ``3.6.3-alpine3.6`` image, or a newer one if available.

**Comment by jantman** [comment]
I don't know if this was happening before or not, but now I can't get phantomJS to run in the Alpine image. It seems like I'm hitting https://github.com/ariya/phantomjs/issues/14186 where PhantomJS just doesn't work on Alpine/musl, and there doesn't seem to be a clear workaround at this time (though it seems like it did with earlier phantom and/or musl versions?)

**Comment by jantman** [comment]
Ok, I managed to find https://github.com/fgrehm/docker-phantomjs2 which provides a working phantomjs on Alpine in Docker, albeit phantomjs 2.0.0 instead of 2.1.1

**Comment by jantman** [comment]
Ok, using the last commit I have acceptance tests passing against an Alpine-based Docker container, and I have phantomjs 2.0.0 running in the container itself.
